### ISSUE TITLE
Call to undefined method Closure::__set_state()

### ISSUE THREAD

**Issue by rhengles** [zendframework/zend-config-aggregator#17]
[Here](https://docs.zendframework.com/zend-servicemanager/configuring-the-service-manager/), it says a factory can be a Callable.

But when the cache file is written, it outputs this:

```php
<?php
return array (
  'dependencies' => 
  array (
    'factories' => 
    array (
      'App\\Model\\MyTable' => 
      Closure::__set_state(array(
      )),
      'App\\Model\\MyTableGateway' => 
      Closure::__set_state(array(
      )),
      /* etc... */
    ),
  ),
);
```

Which causes this error:

```
PHP Fatal error:  Uncaught Error: Call to undefined method Closure::__set_state() in /path/to/project/data/config-cache.php:42
```

It's very strange, because I used PHP 7.2 to create this project, and it didn't cause this error. Now, I installed the same project in another machine, with PHP 7.2 also, and this error began to appear...

*Edit:*

I've since discovered that when checking out the project from version control, it lost the development mode and the "ENABLE_CACHE => false", which is why I didn't have this cache problem before. Still, a config with a Callable can't be cached?

**Comment by Xerkus** [comment]
Works as intended.

Closures are good for development with caching disabled, as you discovered, but they cannot be serialized by php so you have to avoid using them in config providers.
Generally, it is best to avoid using anything that is not safe to serialize.

Other [callable types](https://secure.php.net/manual/en/language.types.callable.php) you can use.

**Comment by RogerWebb** [comment]
I just debugged this same issue and I still feel this is a problem.  If this is a feature, the config cache component should raise an Exception saying so.  Letting the error cascade up to the interpreter leads to unneeded debugging.  If it weren't for this Github issue being indexed on Google, it would have taken me even longer.  If raising a framework exception is not viable for whatever reason (ie. performance) then I would suggest not allowing closures for use in development, where you can spare the expense of checking the config.  Allowing for something crucial, like the app config, to be developed in manner that will explode in production seems, imo, counter-productive despite whatever negligible benefits it may provide during development.
