### ISSUE TITLE
Variable member passed by value to method of same object -- Why?

### ISSUE THREAD

**Issue by nuxwin** [zendframework/zend-config-aggregator#22]
@weierophinney 

Good morning,

After looking at your code, I feel a bit stupid and so I prefer ask you to learn a bit more if needed. 

In the **Zend\ConfigAggregator\ConfigAggregator**, the constructor look as follows:

```php
    public function __construct(
        array $providers = [],
        $cachedConfigFile = null,
        array $postProcessors = []
    ) {
        if ($this->loadConfigFromCache($cachedConfigFile)) {
            return;
        }

        $this->config = $this->loadConfigFromProviders($providers);
        $this->config = $this->postProcessConfig($postProcessors, $this->config);
        $this->cacheConfig($this->config, $cachedConfigFile);
    }
```

So basically put, you get the configuration from the configuration providers, then you post process it with optional post-processors and finally, you cache it if requested.

The question that come to mind here is: why you're passing the **config** member variable by value to methods of same object. For me, doing this mean that you do a copy first in memory, involving useless overhead in my opinion. Why you don't just access the **config** member variable from the called methods directly? Of course these days, this can look as a micro-optimization but I'm really wondering the purpose of such a way.

**Comment by weierophinney** [comment]
It's a lesson I learned from functional programming. Doing it this way makes the methods idempotent and more easily testable.

**Comment by nuxwin** [comment]
@weierophinney 

Thank you for explanation. That's much appreciated ;)
