### ISSUE TITLE
Tag version 1.0

### ISSUE THREAD

**Issue by mtymek** [zendframework/zend-config-aggregator#4]
Looks like this project has proven itself in the wild and I don't see potential compatibility breaks anytime soon. I feel like the time has come to tag v1.0 :-)

**Comment by froschdesign** [comment]
> I feel like the time has come to tag v1.0

I think for a version 1.0 we should:

- [x] create a documentation (ported from the readme file)
- [x] create a new readme file
- [x] create the "develop" branch
- [x] create new milestones
- [x] update the website
- [x] update the documentation homepage

**Comment by mtymek** [comment]
The first version of the documentation is ready: #7. 
I cannot help with other requirements.

**Comment by weierophinney** [comment]
Done! https://github.com/zendframework/zend-config-aggregator/releases/tag/1.0.0

Thanks, @mtymek !
