### ISSUE TITLE
PhpFileProvider isn't loading files

### ISSUE THREAD

**Issue by exts** [zendframework/zend-config-aggregator#8]
Code:

```php
use Zend\ConfigAggregator\ConfigAggregator;
use Zend\ConfigAggregator\PhpFileProvider;

$aggregator = new ConfigAggregator([
    new PhpFileProvider('{,*.}.global.php'),
]);

var_dump($aggregator->getMergedConfig());
```

I have a file in the same folder:

_test.global.php_
```php
return [
    'wtf' =>'boy'
];
```

Output: 

> /var/www/app.dev/tmi/config/config.php:11:
> array (size=0)
>   empty

What exactly am I doing wrong here?

I'm running a vagrant box with ubuntu (trusty64), php 7.1 (recent version).

**Comment by weierophinney** [comment]
Do you have development mode disabled by any chance?

**Comment by exts** [comment]
@weierophinney development mode? I'm using ZCA standalone, unless there's some configuration I'm missing?

**Comment by exts** [comment]
Ah weird, glob() works based on the folder you're loading it from apparently? So for instance:

- /bootstrap.php <- includes config file
- /config/config.php <- where code is stored, which loads the aggregator class
- /public/index.php <- includes bootstrap.php

I had to wrap the config code into a function eg.:

_/config/config.php_
```php
use Zend\ConfigAggregator\ConfigAggregator;
use Zend\ConfigAggregator\PhpFileProvider;

return (function() {
    chdir(root('config'));

    $aggregator = new ConfigAggregator([
        new PhpFileProvider('autoload/{,*.}global.php'),
    ]);

    return $aggregator->getMergedConfig();
})();
```

Which changes the path from the public folder back to the /config folder. Interesting.
